name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            output: analyze-repo-linux-amd64
          - goos: linux
            goarch: arm64
            output: analyze-repo-linux-arm64
          - goos: darwin
            goarch: amd64
            output: analyze-repo-darwin-amd64
          - goos: darwin
            goarch: arm64
            output: analyze-repo-darwin-arm64
          - goos: windows
            goarch: amd64
            output: analyze-repo-windows-amd64.exe
          - goos: windows
            goarch: arm64
            output: analyze-repo-windows-arm64.exe
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23
    
    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Download dependencies
      run: go mod download
    
    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        go build -ldflags "-s -w -X main.version=${{ github.ref_name }}" \
          -o bin/${{ matrix.output }} \
          cmd/analyze-repo/main.go
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binaries
        path: bin/

  release:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: binaries
        path: bin/
    
    - name: Create checksums
      run: |
        cd bin
        sha256sum * > checksums.txt
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          bin/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}